name: publish-pypi

on:
  push:
    tags: v[01].[0-9]+.[0-9]+
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  deploy:
    
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
          pip install .
          pytag pytagged -t develop

      - name: Build & publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          tar -zxvf dist/*.gz
          tail -100 build/lib/pytagged/cli.py
          tail -100 pytagged/cli.py